version: 2
enable-beta-ecosystems: true
updates:
  - package-ecosystem: "npm"
    schedule:
      interval: "daily"
    ignore:
      # ignore patch updates for all dependencies
      - dependency-name: "*"
        update-types: ["version-update:semver-minor"]
